version: "3.9"

services:
  frontend:
    image: ghcr.io/aidanschmitigal/excalidraw:latest
    restart: unless-stopped
    environment:
      - VITE_APP_BACKEND_V2_GET_URL=https://json.test.com/api/v2
      - VITE_APP_BACKEND_V2_POST_URL=https://json.test.com/api/v2/post
      - VITE_APP_WS_SERVER_URL=https://websocket.test.com
    ports:
      - 3200:80

  storage:
    image: ghcr.io/aidanschmitigal/excalidraw-storage-backend:latest
    restart: unless-stopped
    volumes:
      - ./storage:/app/storage
    ports:
      - 3202:8082

  room:
    image: ghcr.io/aidanschmitigal/excalidraw-room:latest
    restart: unless-stopped
    ports:
      - 3204:8084
