# sample comes from https://github.com/docker/awesome-compose

services:
  frontend:
    image: local-excalidraw
    build: ./excalidraw
    restart: unless-stopped
    environment:
      - VITE_APP_BACKEND_V2_GET_URL=https://test.com/api/v2/
      - VITE_APP_BACKEND_V2_POST_URL=https://test.com/api/v2/post/
      - VITE_APP_WS_SERVER_URL=http://127.0.0.1:3204
      - VITE_APP_HTTP_STORAGE_BACKEND_URL=http://127.0.0.1:3202/api/v2
    ports:
      - 80:80

  storage:
    image: local-excalidraw-storage
    build: ./excalidraw-storage-backend
    restart: unless-stopped
    ports:
      - 3202:8080

  room:
    image: local-excalidraw-room
    build: ./excalidraw-room
    restart: unless-stopped
    ports:
      - 3204:8080
