name: Create and publish Docker images

on:
  push:
    branches: ["main"]

env:
  REGISTRY: ghcr.io

jobs:
  build-and-push-images:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3.2.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Build and push for excalidraw
      - name: Extract metadata for Docker (excalidraw)
        id: meta-excalidraw
        uses: docker/metadata-action@v5.5.1
        with:
          tags: type=raw,value=latest
          images: ${{ env.REGISTRY }}/excalidraw

      - name: Build and push Docker image (excalidraw)
        id: push-excalidraw
        uses: docker/build-push-action@v6.2.0
        with:
          context: ./excalidraw
          push: true
          tags: ${{ steps.meta-excalidraw.outputs.tags }}
          labels: ${{ steps.meta-excalidraw.outputs.labels }}

      # Build and push for excalidraw-room
      - name: Extract metadata for Docker (excalidraw-room)
        id: meta-excalidraw-room
        uses: docker/metadata-action@v5.5.1
        with:
          tags: type=raw,value=latest
          images: ${{ env.REGISTRY }}/excalidraw-room

      - name: Build and push Docker image (excalidraw-room)
        id: push-excalidraw-room
        uses: docker/build-push-action@v6.2.0
        with:
          context: ./excalidraw-room
          push: true
          tags: ${{ steps.meta-excalidraw-room.outputs.tags }}
          labels: ${{ steps.meta-excalidraw-room.outputs.labels }}

      # Build and push for excalidraw-storage-backend
      - name: Extract metadata for Docker (excalidraw-storage-backend)
        id: meta-excalidraw-storage-backend
        uses: docker/metadata-action@v5.5.1
        with:
          tags: type=raw,value=latest
          images: ${{ env.REGISTRY }}/excalidraw-storage-backend

      - name: Build and push Docker image (excalidraw-storage-backend)
        id: push-excalidraw-storage-backend
        uses: docker/build-push-action@v6.2.0
        with:
          context: ./excalidraw-storage-backend
          push: true
          tags: ${{ steps.meta-excalidraw-storage-backend.outputs.tags }}
          labels: ${{ steps.meta-excalidraw-storage-backend.outputs.labels }}
